AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pack-lambda

  Sample SAM Template for pack-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180

Resources:
  PackFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pack/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        Pack:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: ./pack
            Method: get
  MyApi:
   Type: AWS::Serverless::Api
   Properties:
     StageName: Pack
     Auth:
       DefaultAuthorizer: MyLambdaTokenAuthorizer
       Authorizers:
         MyLambdaTokenAuthorizer:
           FunctionArn: !GetAtt MyAuthFunction.Arn
  MyAuthFunction:
     Type: AWS::Serverless::Function
     Properties:
       CodeUri: ./pack
       Handler: authorizer.handler
       Runtime: python3.7

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PackApi:
    Description: "API Gateway endpoint URL for packing items"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pack/"
  PackFunction:
    Description: "Packing Lambda Function ARN"
    Value: !GetAtt PackingFunction.Arn
  PackFunctionIamRole:
    Description: "Implicit IAM Role created for pack function"
    Value: !GetAtt PackingFunctionRole.Arn
